#define ANSI_RESET = "\x1b[0m"
#define BOLD_ON =  "\x1b[1m"
#define ITALICS_ON = "\x1b[3m"
#define UNDERLINE_ON = "\x1b[4m"
#define INVERSE_ON = "\x1b[7m"
#define STRIKE_ON  = "\x1b[9m"
#define BOLD_OFF =  "\x1b[22m"
#define ITALICS_OFF "\x1b[23m"
#define UNDERLINE_OFF "\x1b[24m"
#define INVERSE_OFF = "\x1b[27m"
#define STRIKE_OFF = "\x1b[29m"

#define FGBLACK = "\x1b[30m"
#define FGRED = "\x1b[31m"
#define FGGREEN = "\x1b[32m"
#define FGYELLOW = "\x1b[33m"
#define FGBLUE = "\x1b[34m"
#define FGMAGENTA = "\x1b[35m"
#define FGCYAN = "\x1b[36m"
#define FGWHITE = "\x1b[37m
#define FGDEFAULT = "\x1b[39m"

#define BGBLACK = "\x1b[41m"
#define BGRED = "\x1b[42m"
#define BGGREEN = "\x1b[43m"
#define BGYELLOW = "\x1b[44m"
#define BGBLUE = "\x1b[45m"
#define BGMAGENTA "\x1b[46m"
#define BGCYAN = "\x1b[47m"
#define BGWHITE = "\x1b[48m"
#define BGDEFAULT = "\x1b[49m]"